import './globals.css'
import { Rubik } from 'next/font/google'

//components
import Navbar from './components/navbar'

const rubik = Rubik({ subsets: ['latin']})

export const metadata = {
  title: 'Home Page',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
